name: Pages Environment Test (temporary)

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - run: echo "hi, got a runner for the github-pages environment"
